version: '2'

volumes:
  db-data:

services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=demodb
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopwd
    volumes:
      - db-data:/var/lib/postgresql/data:rw
   

