version: '2'

volumes:
  mysqldata:
  db-data:

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'millicom'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    environment:
      DB_USER: demouser
      DB_PASS: demopwd
      DB_NAME: demodb
    volumes:
      - db-data:/var/lib/postgresql/data:rw
   

